use crate::{Factor, FactorIndexGroup, FactorType, Topic, TopicKind, TopicType};

pub fn ask_raw_pipeline_monitor_topic() -> Topic {
    let mut factors = Vec::new();
    factors.push(
        Factor::new()
            .factor_id(String::from("rpml-f-1"))
            .name(String::from("uid"))
            .r#type(FactorType::Text)
            .flatten(true)
            .index_group(FactorIndexGroup::UniqueIndex2)
            .precision(String::from("50")),
    );
    factors.push(
        Factor::new()
            .factor_id(String::from("rpml-f-2"))
            .name(String::from("traceId"))
            .r#type(FactorType::Text)
            .flatten(true)
            .index_group(FactorIndexGroup::Index1)
            .precision(String::from("50")),
    );
    factors.push(
        Factor::new()
            .factor_id(String::from("rpml-f-3"))
            .name(String::from("pipelineId"))
            .r#type(FactorType::Text)
            .flatten(true)
            .index_group(FactorIndexGroup::Index2)
            .precision(String::from("50")),
    );
    factors.push(
        Factor::new()
            .factor_id(String::from("rpml-f-4"))
            .name(String::from("topicId"))
            .r#type(FactorType::Text)
            .flatten(true)
            .index_group(FactorIndexGroup::Index3)
            .precision(String::from("50")),
    );
    factors.push(create_factor(
        "rpml-f-5",
        "prerequisite",
        FactorType::Boolean,
    ));
    factors.push(create_factor(
        "rpml-f-6",
        "prerequisiteDefinedAs",
        FactorType::Object,
    ));
    factors.push(
        Factor::new()
            .factor_id(String::from("rpml-f-7"))
            .name(String::from("status"))
            .r#type(FactorType::Text)
            .flatten(true)
            .precision(String::from("20")),
    );
    factors.push(
        Factor::new()
            .factor_id(String::from("rpml-f-8"))
            .name(String::from("startTime"))
            .r#type(FactorType::FullDatetime)
            .flatten(true),
    );
    factors.push(
        Factor::new()
            .factor_id(String::from("rpml-f-9"))
            .name(String::from("spentInMills"))
            .r#type(FactorType::Unsigned)
            .flatten(true),
    );

    fn create_factor(
        factor_id: &'static str,
        name: &'static str,
        factor_type: FactorType,
    ) -> Factor {
        Factor::new()
            .factor_id(String::from(factor_id))
            .name(String::from(name))
            .r#type(factor_type)
    }

    factors.push(create_factor("rpml-f-10", "error", FactorType::Text));
    factors.push(create_factor("rpml-f-11", "oldValue", FactorType::Object));
    factors.push(create_factor("rpml-f-12", "newValue", FactorType::Object));
    factors.push(create_factor("rpml-f-13", "stages", FactorType::Array));
    factors.push(create_factor(
        "rpml-f-14",
        "stages.stageId",
        FactorType::Text,
    ));
    factors.push(create_factor("rpml-f-15", "stages.name", FactorType::Text));
    factors.push(create_factor(
        "rpml-f-16",
        "stages.prerequisite",
        FactorType::Boolean,
    ));
    factors.push(create_factor(
        "rpml-f-17",
        "stages.prerequisiteDefinedAs",
        FactorType::Object,
    ));
    factors.push(create_factor(
        "rpml-f-18",
        "stages.status",
        FactorType::Text,
    ));
    factors.push(create_factor(
        "rpml-f-19",
        "stages.startTime",
        FactorType::FullDatetime,
    ));
    factors.push(create_factor(
        "rpml-f-20",
        "stages.spentInMills",
        FactorType::Unsigned,
    ));
    factors.push(create_factor("rpml-f-21", "stages.error", FactorType::Text));
    factors.push(create_factor(
        "rpml-f-22",
        "stages.units",
        FactorType::Array,
    ));
    factors.push(create_factor(
        "rpml-f-23",
        "stages.units.unitId",
        FactorType::Text,
    ));
    factors.push(create_factor(
        "rpml-f-24",
        "stages.units.name",
        FactorType::Text,
    ));
    factors.push(create_factor(
        "rpml-f-25",
        "stages.units.prerequisite",
        FactorType::Boolean,
    ));
    factors.push(create_factor(
        "rpml-f-26",
        "stages.units.prerequisiteDefinedAs",
        FactorType::Object,
    ));
    factors.push(create_factor(
        "rpml-f-27",
        "stages.units.loopVariableName",
        FactorType::Text,
    ));
    factors.push(create_factor(
        "rpml-f-28",
        "stages.units.loopVariableValue",
        FactorType::Array,
    ));
    factors.push(create_factor(
        "rpml-f-29",
        "stages.units.status",
        FactorType::Text,
    ));
    factors.push(create_factor(
        "rpml-f-30",
        "stages.units.startTime",
        FactorType::FullDatetime,
    ));
    factors.push(create_factor(
        "rpml-f-31",
        "stages.units.spentInMills",
        FactorType::Unsigned,
    ));
    factors.push(create_factor(
        "rpml-f-32",
        "stages.units.error",
        FactorType::Text,
    ));
    factors.push(create_factor(
        "rpml-f-33",
        "stages.units.actions",
        FactorType::Array,
    ));
    factors.push(create_factor(
        "rpml-f-34",
        "stages.units.actions.uid",
        FactorType::Text,
    ));
    factors.push(create_factor(
        "rpml-f-35",
        "stages.units.actions.actionId",
        FactorType::Text,
    ));
    factors.push(create_factor(
        "rpml-f-36",
        "stages.units.actions.type",
        FactorType::Text,
    ));
    factors.push(create_factor(
        "rpml-f-37",
        "stages.units.actions.insertCount",
        FactorType::Unsigned,
    ));
    factors.push(create_factor(
        "rpml-f-38",
        "stages.units.actions.updateCount",
        FactorType::Unsigned,
    ));
    factors.push(create_factor(
        "rpml-f-39",
        "stages.units.actions.deleteCount",
        FactorType::Unsigned,
    ));
    factors.push(create_factor(
        "rpml-f-40",
        "stages.units.actions.definedAs",
        FactorType::Object,
    ));
    factors.push(create_factor(
        "rpml-f-41",
        "stages.units.actions.findBy",
        FactorType::Object,
    ));
    factors.push(create_factor(
        "rpml-f-42",
        "stages.units.actions.touched",
        FactorType::Object,
    ));
    factors.push(create_factor(
        "rpml-f-43",
        "stages.units.actions.status",
        FactorType::Text,
    ));
    factors.push(create_factor(
        "rpml-f-44",
        "stages.units.actions.startTime",
        FactorType::FullDatetime,
    ));
    factors.push(create_factor(
        "rpml-f-45",
        "stages.units.actions.spentInMills",
        FactorType::Unsigned,
    ));
    factors.push(create_factor(
        "rpml-f-46",
        "stages.units.actions.error",
        FactorType::Text,
    ));
    factors.push(
        Factor::new()
            .factor_id(String::from("rpml-f-47"))
            .name(String::from("dataId"))
            .r#type(FactorType::Number)
            .flatten(true)
            .index_group(FactorIndexGroup::Index4),
    );

    Topic::new()
        .name(String::from("raw_pipeline_monitor_log"))
        .kind(TopicKind::System)
        .r#type(TopicType::Raw)
        .factors(factors)
        .description(String::from("Pipeline monitor log raw topic"))
        .build()
}
